### ISSUE TITLE
the game crashes as i press fire button 

### ISSUE THREAD

**Issue by mahnader** [Carlmundo/W2-Plus#3] opened 2022-07-01 00:23 UTC
when i press fire button  the games crashes . any solution ?  
i have windows 10

**Comment by spudpiggy** [comment] 2023-01-08 11:00
This is caused by some of the des patches that are applied to worms2.exe. I have made Carl aware of this issue and hopefully he will push an update fixing this.

**Comment by Carlmundo** [comment] 2023-01-09 22:01
Fixed in the new release.

**Closed** 2023-01-09 22:01 UTC

**Comment by spudpiggy** [comment] 2023-12-16 15:04
Update on this issue: the 'rope fix' that was originally causing this crash has been replaced with one that works and doesn't crash the game, at least for me.
Next update will include this
