### ISSUE TITLE
w2plus v1.5.7.2 : C++ runtime issue with landgen.exe (GOG version, win 10)

### ISSUE THREAD

**Issue by msbr0815** [Carlmundo/W2-Plus#12] opened 2023-11-17 00:23 UTC
Hi,

First and foremost thanks a lot for taking the time to create the patch. Unfortunately I cannot play the game: After running start.exe, the launcher works fine, but when I try to start a single-player game (haven't tried any other variant), the terrain generator landgen.exe throws an error ("abnormal program termination") and the worms2.exe as well:
![worms-2-gog_win10_landgen-issue](https://github.com/Carlmundo/W2-Plus/assets/47358802/a12d2e7e-6054-4970-94d5-f8e0cd9611e9)
![worms-2-gog_win10_worms-2-issue](https://github.com/Carlmundo/W2-Plus/assets/47358802/4b8aacdc-b8e7-4aec-a5d3-342de023480d)

The frontend then hangs up and crashes.
![worms2-gog_crash](https://github.com/Carlmundo/W2-Plus/assets/47358802/aa2e95b7-6ee2-49fc-9e6a-79d11e882770)

I already (re-)installed the VC++ runtime components from here https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 (I installed both the x86 and x64 versions), but this did not help). Do I need the 2013 version? As for the game itself, I installed it through the gog galaxy client and started start.exe without any compatibility settings. Maybe the non-galaxy setup package from gog makes a difference, even though this would be rather unexpected. Do you have another idea?

Cheers!

**Comment by Carlmundo** [comment] 2023-11-25 19:59
Hello, working on a fix for this. I know what the issue is. Will update you shortly.

**Comment by Carlmundo** [comment] 2023-11-25 21:07
New update released. Please try the latest version.

**Closed** 2023-12-05 15:00 UTC
